# Generated by Django 6.1.1 on 2026-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_waste_analytics_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetrecord",
            name="confidence",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="datasetrecord",
            name="m49_code",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
